const express=require("express");
const http=require("http");
const {Server}=require("socket.io");
const app=express();
const server=http.createServer(app);
const io=new Server(server);
const PORT=process.env.PORT||3000;

app.set("trust proxy",true);
app.use(express.static("public"));
app.get("/health",(q,r)=>r.json({ok:true}));

const tables=new Map();
const SUITS=["♠","♥","♦","♣"],RANKS=["2","3","4","5","6","7","8","9","10","J","Q","K","A"];
const rankValue={2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,J:11,Q:12,K:13,A:14};
const houseWallet={coins:0,totalFees:0};
function deck(){return SUITS.flatMap(s=>RANKS.map(r=>({rank:r,suit:s})));}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function clientKey(s){return s.handshake.headers["x-forwarded-for"]?.split(",")[0]?.trim()||s.handshake.address;}
function newTable(){const id="table-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);const t={id,players:new Map(),round:0,deck:[],turnIndex:0,phase:"waiting",cardNo:0,pot:0,currentChaal:20,discarded:[],winner:null,showdown:null,mode:"classic",modeLabel:"Classic 3 Patti",hukamCard:null,jokerRanks:[]};tables.set(id,t);return t;}
function activePlayers(t){return [...t.players.values()].filter(p=>p.hand.length>0);}
function addBot(t){if([...t.players.values()].some(p=>p.isBot))return [...t.players.values()].find(p=>p.isBot);if(t.players.size>=5)return null;const id="bot-"+Date.now()+"-"+Math.random().toString(36).slice(2,6);const bot={id,key:id,name:"Robo Player",avatar:"",chips:1000,connected:true,hand:[],seen:false,bet:0,round:0,isBot:true};t.players.set(id,bot);return bot;}
function botDraw(t){const ps=[...t.players.values()],bot=ps[t.turnIndex];if(!bot?.isBot||t.phase!=="draw")return;if(bot.hand.length<3){bot.hand.push(t.deck.pop());t.cardNo=bot.hand.length;}const allDealt=[...t.players.values()].filter(x=>x.connected).every(x=>x.hand.length===3);if(allDealt){const first=[...t.players.values()].findIndex(x=>x.connected&&!x.isBot);t.turnIndex=first>=0?first:0;t.phase="action";t.cardNo=3;sendTable(t);if([...t.players.values()][t.turnIndex]?.isBot)setTimeout(()=>botTurn(t),500);return;}let i=t.turnIndex;for(let step=0;step<ps.length;step++){i=(i+1)%ps.length;if(ps[i].connected&&ps[i].hand.length<3){t.turnIndex=i;break;}}sendTable(t);if(ps[t.turnIndex]?.isBot)setTimeout(()=>botDraw(t),450);}
function botTurn(t){const ps=[...t.players.values()],bot=ps[t.turnIndex];if(!bot?.isBot||t.phase!=="action")return;const active=activePlayers(t);if(active.length===1){awardWinner(t,active[0],"last player remaining");sendTable(t);return;}if(!bot.seen){bot.seen=true;sendTable(t);setTimeout(()=>botTurn(t),400);return;}if(active.length===2&&Math.random()<0.25){const other=active.find(x=>x.id!==bot.id),cmp=compareHands(bot.hand,other.hand,t);t.showdown={players:active.map(x=>({id:x.id,name:x.name,cards:x.hand,score:handScore(x.hand,t)})),calledBy:bot.id};if(cmp===0){const gross=t.pot,fee=Math.floor(gross*0.03),net=gross-fee,share=Math.floor(net/2),rem=net-share*2;houseWallet.coins+=fee;houseWallet.totalFees+=fee;bot.chips+=share+rem;other.chips+=share;t.winner={id:null,name:"Tie",reason:"equal hands",grossPot:gross,fee,net};t.pot=0;t.phase="finished";}else awardWinner(t,cmp>0?bot:other,"showdown");sendTable(t);return;}if(Math.random()<0.15&&active.length>2){t.discarded.push({playerId:bot.id,name:bot.name,cards:bot.hand});bot.hand=[];bot.seen=false;nextTurn(t);sendTable(t);if([...t.players.values()][t.turnIndex]?.isBot)setTimeout(()=>botTurn(t),500);return;}const n=Math.max(20,t.currentChaal);if(n>bot.chips){awardWinner(t,active.find(x=>x.id!==bot.id)||bot,"bot out of coins");sendTable(t);return;}bot.chips-=n;bot.bet+=n;t.pot+=n;t.currentChaal=n;nextTurn(t);sendTable(t);if([...t.players.values()][t.turnIndex]?.isBot)setTimeout(()=>botTurn(t),500);}
function baseHandScore(hand){const cards=[...hand].sort((a,b)=>rankValue[b.rank]-rankValue[a.rank]);const vals=cards.map(c=>rankValue[c.rank]);const counts={};vals.forEach(v=>counts[v]=(counts[v]||0)+1);const unique=[...new Set(vals)].sort((a,b)=>b-a);const flush=cards.every(c=>c.suit===cards[0].suit);const straight=unique.length===3&&((unique[0]-unique[unique.length-1]===2)||(unique.join(",")==="14,3,2"));const straightHigh=unique.join(",")==="14,3,2"?3:unique[0];const groups=Object.entries(counts).map(([v,n])=>({v:+v,n})).sort((a,b)=>b.n-a.n||b.v-a.v);if(groups[0]?.n===3)return [6,groups[0].v];if(straight&&flush)return [5,straightHigh];if(straight)return [4,straightHigh];if(flush)return [3,...vals];if(groups[0]?.n===2){const pair=groups.find(g=>g.n===2)?.v||groups[0].v;const kicker=groups.find(g=>g.n===1)?.v||0;return [2,pair,kicker];}return [1,...vals];}
function scoreCmp(x,y){for(let i=0;i<Math.max(x.length,y.length);i++){if((x[i]||0)!==(y[i]||0))return (x[i]||0)>(y[i]||0)?1:-1;}return 0;}
function handScore(hand,t){const jokerRanks=new Set(t?.jokerRanks||[]);const jokers=hand.filter(c=>jokerRanks.has(c.rank));if(!jokers.length)return baseHandScore(hand);const fixed=hand.filter(c=>!jokerRanks.has(c.rank));let best=null;function walk(i,built){if(i===jokers.length){const sc=baseHandScore(fixed.concat(built));if(!best||scoreCmp(sc,best)>0)best=sc;return;}for(const r of RANKS)for(const s of SUITS)walk(i+1,built.concat([{rank:r,suit:s}]));}walk(0,[]);return best||baseHandScore(hand);}
function compareHands(a,b,t){const x=handScore(a,t),y=handScore(b,t),m=t?.mode==="muflis";return m?-scoreCmp(x,y):scoreCmp(x,y);}
function publicTable(t){const ps=[...t.players.values()],current=ps[t.turnIndex];return {tableId:t.id,mode:t.mode,modeLabel:t.modeLabel,hukamCard:t.hukamCard,jokerRanks:t.jokerRanks,players:ps.map((p,i)=>({id:p.id,name:p.name,avatar:p.avatar||"",chips:p.chips,connected:p.connected,bet:p.bet,revealed:p.hand.length,seen:p.seen,hand:t.showdown?p.hand:[],turn:i===t.turnIndex})),pot:t.pot,currentChaal:t.currentChaal,round:t.round,phase:t.phase,cardNo:t.cardNo,discarded:t.discarded,currentPlayerId:current?.id||null,winner:t.winner,showdown:t.showdown};}
function sendTable(t){io.to(t.id).emit("table:update",publicTable(t));t.players.forEach(p=>{const revealAll=t.phase==="finished"&&t.showdown;io.to(p.id).emit("hand",(revealAll||p.seen)?(p.hand||[]):[]);});}
function nextTurn(t){const ps=[...t.players.values()];if(!ps.length){t.phase="waiting";return;}let i=t.turnIndex;for(let step=0;step<ps.length;step++){i=(i+1)%ps.length;if(ps[i].connected&&ps[i].hand.length>0){t.turnIndex=i;t.phase="action";t.cardNo=ps[i].hand.length;return;}}t.phase="finished";}
function awardWinner(t,winner,reason){const gross=t.pot;const fee=Math.floor(gross*0.03);const net=gross-fee;houseWallet.coins+=fee;houseWallet.totalFees+=fee;winner.chips+=net;t.winner={id:winner.id,name:winner.name,reason,grossPot:gross,fee,net};t.pot=0;t.phase="finished";}
function startRound(t,requestedMode){const modes={classic:"Classic 3 Patti",hukam:"HUKAM",ak47:"AK-47",muflis:"Muflis",revolving:"Revolving"};t.mode=modes[requestedMode]?requestedMode:"classic";t.modeLabel=modes[t.mode];t.hukamCard=null;t.jokerRanks=[];t.deck=shuffle(deck());if(t.mode==="hukam"){t.hukamCard=t.deck.pop();t.jokerRanks=[t.hukamCard.rank];}else if(t.mode==="revolving"){const picks=[];while(picks.length<3){const card=t.deck.pop();if(!picks.some(x=>x.rank===card.rank))picks.push(card);}t.jokerRanks=picks.map(x=>x.rank);t.revolvingCards=picks;}else if(t.mode==="ak47"){t.jokerRanks=["A","K","4","7"];}t.round++;t.pot=0;t.currentChaal=20;t.turnIndex=0;t.phase="draw";t.cardNo=0;t.discarded=[];t.winner=null;t.showdown=null;t.players.forEach(p=>{p.hand=[];p.bet=0;p.seen=false;p.round=t.round;});sendTable(t);setTimeout(()=>dealNextCard(t),500);}
function dealNextCard(t){if(!tables.has(t.id)||t.phase!=="draw")return;const ps=[...t.players.values()].filter(p=>p.connected);if(!ps.length)return;const current=ps[t.turnIndex];if(!current){t.turnIndex=0;return dealNextCard(t);}if(current.hand.length<3){const card=t.deck.pop();current.hand.push(card);t.cardNo=current.hand.length;sendTable(t);}const allDealt=ps.every(p=>p.hand.length===3);if(allDealt){t.turnIndex=[...t.players.values()].findIndex(p=>p.connected);if(t.turnIndex<0)t.turnIndex=0;t.phase="action";t.cardNo=3;sendTable(t);return;}let next=(t.turnIndex+1)%ps.length;for(let step=0;step<ps.length;step++){if(ps[next].hand.length<3)break;next=(next+1)%ps.length;}const nextPlayer=ps[next];t.turnIndex=[...t.players.values()].findIndex(p=>p.id===nextPlayer.id);setTimeout(()=>dealNextCard(t),650);}
io.on("connection",s=>{const key=clientKey(s);s.on("player:join",(d,a)=>{for(const t of tables.values()){if(t.players.size<5&&!([...t.players.values()].some(p=>p.key===key&&p.connected))){const p={id:s.id,key,name:String(d?.name||"Player").slice(0,20),avatar:typeof d?.avatar==="string"&&d.avatar.length<1500000?d.avatar:"",chips:1000,connected:true,hand:[],seen:false,bet:0,round:0};t.players.set(s.id,p);s.join(t.id);a?.({ok:true,tableId:t.id,tableNumber:t.id});sendTable(t);return;}}const t=newTable(),p={id:s.id,key,name:String(d?.name||"Player").slice(0,20),avatar:typeof d?.avatar==="string"&&d.avatar.length<1500000?d.avatar:"",chips:1000,connected:true,hand:[],seen:false,bet:0,round:0};t.players.set(s.id,p);s.join(t.id);a?.({ok:true,tableId:t.id,tableNumber:t.id});sendTable(t);});
  s.on("round:start",(d,a)=>{const t=tables.get(d?.tableId);if(!t||!t.players.has(s.id))return a?.({ok:false,error:"Table not found"});if(t.players.size===1)addBot(t);if(t.phase!=="waiting"&&t.phase!=="finished")return a?.({ok:false,error:"Round already running"});startRound(t,d?.mode);a?.({ok:true});});
  s.on("draw",(d,a)=>{const t=tables.get(d?.tableId),p=t?.players.get(s.id),ps=t?[...t.players.values()]:[];if(!p||!t||t.phase!=="draw"||ps[t.turnIndex]?.id!==s.id)return a?.({ok:false,error:"Abhi aapki turn nahi hai"});if(p.hand.length>=3)return a?.({ok:false,error:"Aapke 3 cards already hain"});const card=t.deck.pop();p.hand.push(card);t.cardNo=p.hand.length;const allDealt=[...t.players.values()].filter(x=>x.connected).length>0&&[...t.players.values()].filter(x=>x.connected).every(x=>x.hand.length===3);if(allDealt){t.turnIndex=[...t.players.values()].findIndex(x=>x.connected);t.phase="action";t.cardNo=3;}else{let i=t.turnIndex;for(let step=0;step<ps.length;step++){i=(i+1)%ps.length;if(ps[i].connected&&ps[i].hand.length<3){t.turnIndex=i;break;}}t.phase="draw";}sendTable(t);a?.({ok:true});if([...t.players.values()][t.turnIndex]?.isBot)setTimeout(()=>botDraw(t),450);});
  s.on("view",(d,a)=>{const t=tables.get(d?.tableId),p=t?.players.get(s.id),ps=t?[...t.players.values()]:[];if(!p||!t||t.phase!=="action"||ps[t.turnIndex]?.id!==s.id)return a?.({ok:false,error:"Abhi aapki turn nahi hai"});p.seen=true;sendTable(t);a?.({ok:true});});
  s.on("bet",(d,a)=>{const t=tables.get(d?.tableId),p=t?.players.get(s.id),ps=t?[...t.players.values()]:[],n=Math.floor(Number(d?.amount));if(!p||!t||t.phase!=="action"||ps[t.turnIndex]?.id!==s.id)return a?.({ok:false,error:"Abhi aapki turn nahi hai"});if(!Number.isFinite(n)||n<20)return a?.({ok:false,error:"Chaal minimum 20 coin hai"});if(n<t.currentChaal)return a?.({ok:false,error:"Chaal "+t.currentChaal+" se kam nahi ho sakti"});if(n>p.chips)return a?.({ok:false,error:"Aapke paas itne coins nahi hain"});p.chips-=n;p.bet+=n;t.pot+=n;t.currentChaal=n;nextTurn(t);sendTable(t);a?.({ok:true});if([...t.players.values()][t.turnIndex]?.isBot)setTimeout(()=>botTurn(t),500);});
  s.on("pack",(d,a)=>{const t=tables.get(d?.tableId),p=t?.players.get(s.id),ps=t?[...t.players.values()]:[];if(!p||!t||t.phase!=="action"||ps[t.turnIndex]?.id!==s.id)return a?.({ok:false,error:"Abhi aapki turn nahi hai"});if(p.hand.length)t.discarded.push({playerId:p.id,name:p.name,cards:p.hand});p.hand=[];p.seen=false;const active=activePlayers(t);if(active.length===1){awardWinner(t,active[0],"last player remaining");sendTable(t);return a?.({ok:true,winner:active[0].id});}nextTurn(t);sendTable(t);a?.({ok:true});if([...t.players.values()][t.turnIndex]?.isBot)setTimeout(()=>botTurn(t),500);});
  s.on("show",(d,a)=>{const t=tables.get(d?.tableId),p=t?.players.get(s.id);if(!p||!t||t.phase!=="action"||!p.hand.length)return a?.({ok:false,error:"Show abhi available nahi hai"});const active=activePlayers(t);if(active.length!==2)return a?.({ok:false,error:"Show sirf 2 players remaining hone par hoga"});const other=active.find(x=>x.id!==p.id),cmp=compareHands(p.hand,other.hand,t);t.showdown={players:active.map(x=>({id:x.id,name:x.name,cards:x.hand,score:handScore(x.hand)})),calledBy:p.id};if(cmp===0){const gross=t.pot,fee=Math.floor(gross*0.03),net=gross-fee,share=Math.floor(net/2),rem=net-share*2;houseWallet.coins+=fee;houseWallet.totalFees+=fee;p.chips+=share+rem;other.chips+=share;t.winner={id:null,name:"Tie",reason:"equal hands",grossPot:gross,fee,net};t.pot=0;t.phase="finished";}else awardWinner(t,cmp>0?p:other,"showdown");sendTable(t);a?.({ok:true,winner:t.winner});});
  s.on("disconnect",()=>{for(const t of tables.values()){const p=t.players.get(s.id);if(!p)continue;p.connected=false;sendTable(t);setTimeout(()=>{if(t.players.get(s.id)?.connected===false){const wasTurn=[...t.players.values()][t.turnIndex]?.id===s.id; t.players.delete(s.id);const ps=[...t.players.values()];if(!ps.length){tables.delete(t.id);return;}if(t.turnIndex>=ps.length)t.turnIndex=0;if(wasTurn)t.phase=t.phase==="waiting"?"waiting":"draw";sendTable(t);}},30000);break;}});
});
server.listen(PORT,()=>console.log("Teen Patti server on "+PORT));